In [4]:
import pandas as pd
df = pd.read_csv('Final.csv')
print(df)

      Unnamed: 0       Entity Code  Year  Cellular Subscription  \
0              0  Afghanistan  AFG  1980               0.000000   
1              1  Afghanistan  AFG  1981               0.000000   
2              2  Afghanistan  AFG  1982               0.000000   
3              3  Afghanistan  AFG  1983               0.000000   
4              4  Afghanistan  AFG  1984               0.000000   
...          ...          ...  ...   ...                    ...   
8862        8862     Zimbabwe  ZWE  2016              91.793457   
8863        8863     Zimbabwe  ZWE  2017              98.985077   
8864        8864     Zimbabwe  ZWE  2018              89.404869   
8865        8865     Zimbabwe  ZWE  2019              90.102287   
8866        8866     Zimbabwe  ZWE  2020              88.755806   

      Internet Users(%)  No. of Internet Users  Broadband Subscription  
0              0.000000                      0                0.000000  
1              0.000000                      0   

In [3]:
print(dataset.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8867 entries, 0 to 8866
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Unnamed: 0              8867 non-null   int64  
 1   Entity                  8867 non-null   object 
 2   Code                    8867 non-null   object 
 3   Year                    8867 non-null   int64  
 4   Cellular Subscription   8867 non-null   float64
 5   Internet Users(%)       8867 non-null   float64
 6   No. of Internet Users   8867 non-null   int64  
 7   Broadband Subscription  8867 non-null   float64
dtypes: float64(3), int64(3), object(2)
memory usage: 554.3+ KB
None


In [5]:
import pandas as pd
df = pd.read_csv('Final.csv')
print(df)

      Unnamed: 0       Entity Code  Year  Cellular Subscription  \
0              0  Afghanistan  AFG  1980               0.000000   
1              1  Afghanistan  AFG  1981               0.000000   
2              2  Afghanistan  AFG  1982               0.000000   
3              3  Afghanistan  AFG  1983               0.000000   
4              4  Afghanistan  AFG  1984               0.000000   
...          ...          ...  ...   ...                    ...   
8862        8862     Zimbabwe  ZWE  2016              91.793457   
8863        8863     Zimbabwe  ZWE  2017              98.985077   
8864        8864     Zimbabwe  ZWE  2018              89.404869   
8865        8865     Zimbabwe  ZWE  2019              90.102287   
8866        8866     Zimbabwe  ZWE  2020              88.755806   

      Internet Users(%)  No. of Internet Users  Broadband Subscription  
0              0.000000                      0                0.000000  
1              0.000000                      0   

In [8]:
df["Order Zipcode"].fillna("empty", inplace = True)
print(df.info())


KeyError: 'Order Zipcode'

In [9]:
import pandas as pd
df = pd.read_csv('Data_Set.csv')
print(df)

            Type  Days for shipping (real)  Days for shipment (scheduled)  \
0           CASH                         2                              4   
1        PAYMENT                         3                              4   
2        PAYMENT                         3                              4   
3        PAYMENT                         3                              4   
4           CASH                         5                              4   
...          ...                       ...                            ...   
180514  TRANSFER                         6                              4   
180515     DEBIT                         2                              4   
180516     DEBIT                         3                              4   
180517   PAYMENT                         4                              4   
180518      CASH                         1                              0   

        Benefit per order  Sales per customer   Delivery Status  \
0       

In [10]:
df["Order Zipcode"].fillna("empty", inplace = True)
print(df.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype  
---  ------                         --------------   -----  
 0   Type                           180519 non-null  object 
 1   Days for shipping (real)       180519 non-null  int64  
 2   Days for shipment (scheduled)  180519 non-null  int64  
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object 
 6   Late_delivery_risk             180519 non-null  int64  
 7   Category Id                    180519 non-null  int64  
 8   Category Name                  180519 non-null  object 
 9   Customer City                  180519 non-null  object 
 10  Customer Country               180519 non-null  object 
 11  Customer Email                 180519 non-null  object 
 12  Customer Fname                

In [11]:
print(df["Customer Id"])

0         11599
1           256
2           256
3           256
4          8827
          ...  
180514    20753
180515    20754
180516    20755
180517    20756
180518    20757
Name: Customer Id, Length: 180519, dtype: int64


In [12]:
df.loc[3, "Customer Id"] = 45
print(df["Customer Id"])
print(df.index)

0         11599
1           256
2           256
3            45
4          8827
          ...  
180514    20753
180515    20754
180516    20755
180517    20756
180518    20757
Name: Customer Id, Length: 180519, dtype: int64
RangeIndex(start=0, stop=180519, step=1)


In [14]:
for x in df.index:
    if df.loc[x, "Product Price"] > 250:
        df.loc[x, "Product Price"] = 245
        
print(df["Product Price"])

0         245.000000
1         199.990005
2         129.990005
3          50.000000
4          24.990000
             ...    
180514    215.820007
180515    215.820007
180516    245.000000
180517     11.540000
180518     39.750000
Name: Product Price, Length: 180519, dtype: float64


In [ ]:
for x in df.index:
    if df.loc[x, "Product Price"] > 240:
        df.drop(x, inplace = True)
                
        
print(df["Product Price"])
print(df.info())


In [ ]:
for x in df.index:
    if df.loc[x, "Product Price"] > 240:
        df.drop(x, inplace = True)
                      
print(df["Product Price"])
print(df.info())


In [17]:
for x in df.index:
    if df.loc[x, "Product Price"] > 240:
        df.drop(x, inplace = True)
                      
print(df["Product Price"])
print(df.info())


KeyboardInterrupt: 

In [18]:
df.corr()

/var/folders/1k/byvz5y1s6yjf6_1r_snyw26h0000gn/T/ipykernel_50218/1134722465.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()


Days for shipping (real)  \
Days for shipping (real)                       1.000000   
Days for shipment (scheduled)                  0.516465   
Benefit per order                             -0.003719   
Sales per customer                             0.001218   
Late_delivery_risk                             0.400693   
Category Id                                   -0.000733   
Customer Id                                    0.003307   
Customer Zipcode                              -0.000441   
Department Id                                 -0.002164   
Latitude                                      -0.004224   
Longitude                                      0.004344   
Order Customer Id                              0.003307   
Order Id                                      -0.001543   
Order Item Cardprod Id                        -0.001313   
Order Item Discount                            0.002408   
Order Item Discount Rate                       0.001857   
Order Item Id                                 -0.001608   
Order Item Product Price                       0.001624   
Order Item Profit Ratio                       -0.003686   
Order Item Quantity                           -0.000505   
Sales                                          0.001497   
Order Item Total                               0.001218   
Order Profit Per Order                        -0.003719   
Product Card Id                               -0.001313   
Product Category Id                           -0.000733   
Product Description                                 NaN   
Product Price                                 -0.000321   
Product Status                                      NaN   

                               Days for shipment (scheduled)  \
Days for shipping (real)                            0.516465   
Days for shipment (scheduled)                       1.000000   
Benefit per order                                  -0.000019   
Sales per customer                                  0.006272   
Late_delivery_risk                                 -0.369298   
Category Id                                        -0.000913   
Customer Id                                         0.000634   
Customer Zipcode                                   -0.003373   
Department Id                                      -0.000977   
Latitude                                           -0.005990   
Longitude                                           0.003844   
Order Customer Id                                   0.000634   
Order Id                                           -0.001067   
Order Item Cardprod Id                             -0.001039   
Order Item Discount                                 0.003333   
Order Item Discount Rate                            0.000359   
Order Item Id                                      -0.001031   
Order Item Product Price                            0.006809   
Order Item Profit Ratio                            -0.001798   
Order Item Quantity                                -0.002511   
Sales                                               0.006231   
Order Item Total                                    0.006272   
Order Profit Per Order                             -0.000019   
Product Card Id                                    -0.001039   
Product Category Id                                -0.000913   
Product Description                                      NaN   
Product Price                                       0.002706   
Product Status                                           NaN   

                               Benefit per order  Sales per customer  \
Days for shipping (real)               -0.003719            0.001218   
Days for shipment (scheduled)          -0.000019            0.006272   
Benefit per order                       1.000000            0.136216   
Sales per customer                      0.136216            1.000000   
Late_delivery_risk                     -0.002984           -0.005174   
Category Id                   

In [20]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [22]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [23]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [24]:
arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [25]:
print(arr[2] +arr[3])

7


In [26]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])
print(arr[:4])

[5 6 7]
[1 2 3 4]


In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [29]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [30]:
from numpy import random

x = random.randint(100)

print(x)

2


In [31]:
x = random.randint(100)

print(x)

89


In [32]:
x = random.randint(100)

print(x)

4


In [33]:
x = random.randint(100)

print(x)

38


In [34]:
x = random.randint(100)

print(x)

52


In [35]:
x = random.randint(100)

print(x)

37


In [36]:
x = random.randint(100)

print(x)

86


In [37]:
x = random.randint(100)

print(x)

83


In [38]:
x = random.randint(100)

print(x)

17


In [39]:
x = random.randint(100)

print(x)

2


In [40]:
x = random.randint(100)

print(x)

75


In [41]:
x = random.randint(100)

print(x)

88


In [42]:
x = random.randint(100)

print(x)

44


In [43]:
x = random.randint(100)

print(x)

41


In [44]:
x = random.randint(100)

print(x)

30


In [45]:
x = random.randint(100)

print(x)

67


In [46]:
x = random.randint(100)

print(x)

77


In [47]:
x = random.randint(100)

print(x)

84


In [48]:
x = random.randint(100)

print(x)

23


In [49]:
x = random.randint(100)

print(x)

15


In [50]:
x = random.randint(100)

print(x)

92


In [51]:
x = random.randint(100)

print(x)

55


In [52]:
x = random.randint(100)

print(x)

27


In [53]:
x = random.randint(100)

print(x)

63


In [54]:
x = random.randint(100)

print(x)

3


In [55]:
x = random.randint(100)

print(x)

37


In [56]:
x = random.randint(100)

print(x)

47


In [57]:
x = random.randint(100)

print(x)

14


In [58]:
x = random.randint(100)

print(x)

13


In [59]:
x = random.randint(100)

print(x)

58


In [60]:
x = random.randint(100)

print(x)

42


In [61]:
x = random.randint(100)

print(x)

92


In [62]:
from numpy import random

x = random.rand()

print(x)

0.4614806875556151


In [64]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[34 50 53 73 33]
 [43 59 54 15 84]
 [96  5 26 65 49]]


In [66]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[7 7 7 5 5 7 3 7 7 7 3 7 5 5 5 7 5 7 7 7 7 3 7 7 7 7 7 7 7 5 7 7 7 7 5 7 3
 7 5 7 7 5 7 7 5 5 5 7 7 5 7 7 7 7 5 5 5 7 7 7 7 7 5 7 7 5 7 5 7 7 5 7 7 7
 7 5 3 7 5 7 7 3 7 7 7 7 5 7 7 7 7 7 7 5 7 7 7 7 7 5]


In [67]:
arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)
print(arr)

[1 5 3 2 4]


In [68]:
x = random.normal(loc=1, scale=2, size=(2, 3))
print(x)

[[ 3.67407679  2.19378542 -0.12483363]
 [ 4.09857695 -2.51058438 -1.54441453]]
